services:
  - type: web
    runtime: "node"
    name: rainbow-posting-api

    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PORT
        value: 3000
